### ISSUE TITLE
Crash on Google Flights Page

### ISSUE THREAD

**Issue by deldrid1** [ziolko/aria-devtools#21] opened 2022-02-10 22:55 UTC
I was testing with this tool to understand it in the context of a full ARIA implementation, and was trying on a Google Flights page: https://www.google.com/travel/flights/s/dWU2

Seems to work fine on `flights.google.com` but breaks once you get into the search.  I'll try cloning and messing with the source code, but I've never done any Chrome extension work and am new to ARIA, so I'm afraid its above my paygrade!

```
9inject.js:12 TypeError: Cannot read properties of undefined (reading 'trim')
    at B (inject.js:166:2002)
    at Array.map (<anonymous>)
    at B (inject.js:166:1935)
    at inject.js:116:1948
    at inject.js:44:3245
    at inject.js:44:3074
    at Se (inject.js:42:10232)
    at e.track (inject.js:42:22134)
    at m (inject.js:44:3051)
    at i (inject.js:44:3225)
_o @ inject.js:12
inject.js:8 Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
    at B (inject.js:166:2002)
    at Array.map (<anonymous>)
    at B (inject.js:166:1935)
    at inject.js:116:1948
    at inject.js:44:3245
    at inject.js:44:3074
    at Se (inject.js:42:10232)
    at e.track (inject.js:42:22134)
    at m (inject.js:44:3051)
    at i (inject.js:44:3225)
```

**Comment by sgregson** [comment] 2022-02-23 17:11
FYI I ran into the same issue and opened a quick patch to fix.

I tested the PR #23 on the google flights page referenced in this issue, as well as a vanilla google search results page (and some other personal pages where I was reproducing the issue)

**Comment by ziolko** [comment] 2022-02-28 14:17
Hi @deldrid1 and @sgregson, 

Interestingly, the issue was is caused by the fact that a non-standard aria role "text" is used on this page. I've improved handling of this case so that it won't cause the crash but will show an information about invalid role instead.

![image](https://user-images.githubusercontent.com/495157/155979874-7e433c1b-91f3-48f6-ac37-05889a268be5.png)

I've submitted the new version to the Chrome and Firefox stores so it should be available for you in a day or two. Please confirm that it works well tomorrow or on Wednesday.

**Comment by ziolko** [comment] 2022-03-03 12:25
Could you please confirm that it works for you?

Also, if it does please leave the extension a positive review at [Chrome web store](https://chrome.google.com/webstore/detail/aria-devtools/dneemiigcbbgbdjlcdjjnianlikimpck.). This is a free tool and a good word is the reward I get for spending my time on improving it.

**Comment by sgregson** [comment] 2022-03-03 16:53
Looks fixed on the version in the chrome web store – functional on flights.google.com with the text role callout ! Thanks for patching, I'll definitely review enthusiastically

(I had to restart my browser to clear some extension errors after install)

**Closed** 2022-03-08 20:01 UTC
